[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = [
    "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/",
    "@openzeppelin/contracts-upgradeable/=lib/openzeppelin-contracts-upgradeable/contracts/",
    "@layerzerolabs/lz-evm-oapp-v2/=lib/LayerZero-v2/packages/layerzero-v2/evm/oapp/",
    "@layerzerolabs/lz-evm-protocol-v2/=lib/LayerZero-v2/packages/layerzero-v2/evm/protocol/",
    "@layerzerolabs/lz-evm-messagelib-v2/=lib/LayerZero-v2/packages/layerzero-v2/evm/messagelib/",
    "solidity-bytes-utils/=lib/solidity-bytes-utils/",
    "poseidon-solidity/=lib/poseidon-solidity/",
]
optimizer = true
optimizer_runs = 200
via_ir = false

[lint]
ignore = ["src/verifiers/*"]

[rpc_endpoints]
al-arb-sep = "https://arb-sepolia.g.alchemy.com/v2/${ALCHEMY_KEY}"
al-base-sep = "https://base-sepolia.g.alchemy.com/v2/${ALCHEMY_KEY}"
al-op-sep = "https://opt-sepolia.g.alchemy.com/v2/${ALCHEMY_KEY}"
al-sep = "https://eth-sepolia.g.alchemy.com/v2/${ALCHEMY_KEY}"
al-bnb-test="https://bnb-testnet.g.alchemy.com/v2/${ALCHEMY_KEY}"
localhost = "http://localhost:8545"
